name: remoteopenfast
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - dash
  - dash-bootstrap-components
  - pandas
  - plotly
  - pyyaml
  - numpy
  - pip
  - openfast-io
  - requests
  - tqdm
  - pip:
    - dash-extensions
